apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "functest.fullname" . }}
  labels:
    {{- include "functest.labels" . | nindent 4 }}
data:
  dbcm_config.yaml: |
    {{- toYaml .Values.dbcmconfig | nindent 4 }}
