apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "functests.fullname" . }}
  labels:
    {{- include "functests.labels" . | nindent 4 }}
data:
  dbcm_config.yaml: |
    {{- toYaml .Values.dbcmconfig | nindent 4 }}
