apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromedriver
  labels:
    app: chromedriver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromedriver
  template:
    metadata:
      labels:
        app: chromedriver
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: chromedriver
        image: selenium/standalone-chrome:3.141.59
        ports:
        - containerPort: 4444
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
