# https://github.com/terraform-docs/gh-actions

name: Generate Terraform-Docs && Helm-Docs
on:
  pull_request:
    branches: 
      - main
    paths: 
      - 'charts/**'
      - 'terraform/**'
      - '.github/workflows/**'
      - '.github/templates/**'


jobs:
  call-workflow: 
    uses: hpi-schul-cloud/infra-tools/.github/workflows/generate-tf-helm-docs.yaml@tf-helm-docs-v1
    with:
      name: "devops"
      email: "devops@dbildungscloud.de"
      src_path_tf: terraform
      terraform_docs_config_file: .github/templates/.terraform-docs.yaml 
      src_path_helm: charts
      helm_docs_template_file: .github/templates/README.md.gotmpl
      helm_ignored_dirs: sc-sshd,sc-cert-manager-clusterissuer

